[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12",
    "flask>=2.3",
    "flask-cors>=4.0",
    "python-dotenv>=1.1.1",
    "requests>=2.31",
]
